
CREATE DATABASE instituto;

USE INSTITUTO;

CREATE TABLE ASIGNATURAS
   (IDASIGNATURAS INT AUTO_INCREMENT NOT NULL, 
	NOMBRE VARCHAR(4000) NOT NULL, 
	HORAS INT, 
	PRIMARY KEY (IDASIGNATURAS)
   );

CREATE TABLE  DEPARTAMENTOS
   (IDDEPARTAMENTOS INT AUTO_INCREMENT NOT NULL, 
	NOMBRE VARCHAR(4000) NOT NULL, 
	 PRIMARY KEY (IDDEPARTAMENTOS)
   );

CREATE TABLE  PROFESORES
   (IDPROFESORES INT AUTO_INCREMENT NOT NULL, 
	NOMBRE VARCHAR(4000) NOT NULL, 
	APE1 VARCHAR(4000), 
	APE2 VARCHAR(4000), 
	TFNO VARCHAR(4000), 
	IDDEPARTAMENTOS INT NOT NULL, 
	CONSTRAINT PROF_DEPTO_FK FOREIGN KEY (IDDEPARTAMENTOS)
	  REFERENCES  DEPARTAMENTOS(IDDEPARTAMENTOS)
		ON DELETE CASCADE
        ON UPDATE CASCADE,
	PRIMARY KEY (IDPROFESORES)
   );

CREATE TABLE  PROFESORES_ASIGNATURAS
   (IDPROFESORES INT NOT NULL, 
	IDASIGNATURAS INT NOT NULL, 
	 CONSTRAINT PROFESORES_FK FOREIGN KEY (IDPROFESORES)
	  REFERENCES  PROFESORES(IDPROFESORES)
		ON DELETE CASCADE
        ON UPDATE CASCADE, 
	 CONSTRAINT ASIGNATURAS_FK FOREIGN KEY (IDASIGNATURAS)
	  REFERENCES  ASIGNATURAS(IDASIGNATURAS) 
		ON DELETE CASCADE
        ON UPDATE CASCADE,
	 PRIMARY KEY (IDPROFESORES, IDASIGNATURAS)
   );

CREATE PROCEDURE PA_CONSULTAASIGNATURAS()
	SELECT Nombre, Horas FROM asignaturas;

CREATE PROCEDURE PA_INSERTAASIGNATURA
(IN nomasig VARCHAR(100),
	IN horasasig INT)
	INSERT INTO Asignaturas (nombre,horas) VALUES (nomasig, horasasig);
